'\" t
.ds GVER 1.22.4
.ds MacName lilypond
.ds MacNameCap LILYPOND
.TH GROFF_\*[MacNameCap] 7 "21 november 2022" "groff \*[GVER]"
.SH NAME
groff_\*[MacName] \- GNU roff  macro package for using lilypond files to create pdf-files.
.
.
.\" Save and disable compatibility mode (for, e.g., Solaris 10/11).
.do nr groff_\*MacName_C \n[.C]
.cp 0
.
.
.\" ====================================================================
.\" Legal Terms
.\" ====================================================================
.\"
.\" Copyright (C) 1989-2018 Free Software Foundation, Inc.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of
.\" this manual under the conditions for verbatim copying, provided that
.\" the entire resulting derived work is distributed under the terms of
.\" a permission notice identical to this one.
.\"
.\" Permission is granted to copy and distribute translations of this
.\" manual into another language, under the above conditions for
.\" modified versions, except that this permission notice may be
.\" included in translations approved by the Free Software Foundation
.\" instead of in the original English.
.
.
.\" ====================================================================
.SH SYNOPSIS
.\" ====================================================================
.
.SY ".mso \*[MacName].tmac"
.
.
.\" ====================================================================
.SH DESCRIPTION
.\" ====================================================================
.
The
.I \*[MacName]
macro package provides macros to covert .ly files into pdf-files which 
can be added either inline or as a standalone figure.
.
.
.\" ====================================================================
.SH USAGE
.\" ====================================================================
.
The
.I \*[MacName]
macro packages provides two macros:
.SS LILY
This macro takes a lilypond file (.ly) as argument and converts this into
a pdf.
.SS LILYIN
This macro takes a lilypond file (.ly) as an argument and converts this into a pdf
which is scaled to the current pointsize and is placed inline.
.
.\" ====================================================================
.SH FILES
.\" ====================================================================
.
.I \*[MacName].tmac
.
.
.
.\" ====================================================================
.SH AUTHORS
.\" ====================================================================
The
.I \*[MacName] 
macro package was written by Hans Bezemer and contributors
.
This document was written by
.MT hbezemer@\:kliksafe.nl
Hans Bezemer
.ME .
.
.
.\" ====================================================================
.SH "SEE ALSO"
.\" ====================================================================
.
.BR groff (1),
.BR troff (1),
.BR lilypond (1)
.
.
.PP
.IR "Groff: The GNU Implementation of troff" ,
by Trent A.\& Fisher and Werner Lemberg
.
.
.\" Restore compatibility mode (for, e.g., Solaris 10/11).
.cp \n[groff_\*[MacName]_C]
.
.
.\" Local Variables:
.\" mode: nroff
.\" End:
.\" vim: set filetype=groff:
